source 'https://rubygems.org'

gem 'sinatra'
gem 'mysql2'
gem 'sinatra-contrib'
gem 'sinatra-authorization'
gem 'will_paginate'
gem 'padrino-helpers'
gem 'thin'
gem 'data_mapper'
gem 'dm-mysql-adapter'
